### PR TITLE
WIP : Master interface sweeping

### PR DESCRIPTION
**Pull request by mrvoorhe**
Looking for feedback on whether I should introduce a switch to turn interface sweeping on/off so that we could leave it off for some Managed Stripping Level values and on for others.

This PR introduces two new behavior changes

* Interfaces on a type will no longer be marked simply because the type is marked.  Instead, marking of interfaces on types is deferred until that interface type is marked for some other reason.

* When a type has no instance constructors marked, we will remove all interfaces from that type (because no instance can possibly exist).

Look at the test changes to see examples of various scenarios that will change.

The question to me is, is the impact on reflection scenarios significant enough that it could be annoying to have this on during the `Low` or `Medium` levels?

### CODE REVIEW

**Comment by joshpeterson** [comment]
I'm in favor of turning this on wherever we can. I don't think it is too dangerous for most code.

**Review by joshpeterson — APPROVED** [review]

**Comment by mrvoorhe** [comment]
If we do turn this on across the board, I think we will want some way to stop this behavior via link.xml.  Would you agree @joshpeterson ?  

There is no existing link.xml mechanism that would let you prevent interface sweeping.

**Comment by joshpeterson** [comment]
Could we say that any type preserved via link.xml will not be subject to interface sweeping?

**Comment by mrvoorhe** [comment]
We could, but I don't think that makes sense in all use cases.

For example, intuitively I don't think it makes sense to preserve interfaces during the following.

`<type name="foo" preserve="fields">`
`<type name="foo" preserve="methods">`

It would probably make sense during.

`<type name="foo" preserve="all">`

And then there's the question of what to do during

`<type name="foo" preserve="none">`

I was thinking of adding a new preserve value

`<type name="foo" preserve="interfaces">`

but I haven't fully thought it out yet.

**Comment by joshpeterson** [comment]
I like the idea of `<type name="foo" preserve="interfaces">`. That, and `<type name="foo" preserve="all">` should preserve interfaces. I don't think any of the other cases should.

**Comment by jechter** [comment]
I agree with everything @joshpeterson wrote.

**Review by jechter — APPROVED** [review]

**Comment by joncham** [comment]
Agree with @joshpeterson as well.

**Review by joncham — APPROVED** [review]

**Pull request closed without merging**
